feat: add Facebook authentication support
Stacked-Org/firebase_auth pull request #17
Opened 2024-02-06 08:04 UTC by n0mad-d3v

Hello to the whole Stacked team and thanks again for this nice framework!

In this PR, 
* I added back Facebook authentication via the [flutter_facebook_auth package](https://pub.dev/packages/flutter_facebook_auth) ; 
* I wrote a first documentation on how to use this package ; 
* I created an example application with Google, Facebook and Apple authentication on iOS and Android. The commited example have no secrets left, meaning it's not working out of the box, but here are some videos I did to illustrate the behavior. 

https://github.com/Stacked-Org/firebase_auth/assets/116424218/c35b1a38-ce11-4868-94a5-9aecd806b4e9

Let me know what you think! 🙏

_Christophe_

2024-02-06 11:14 UTC, FilledStacks commented
This is really awesome @n0mad-d3v ! We'll review this and release in this week. 

I appreciate the PR a lot.

2024-02-06 20:16 UTC, ferrarafer requested changes
Hi @n0mad-d3v, great work ! I'm very happy to see people doing collaboration to the framework. Thanks you very much ❤️ 

Please, do the small changes I requested and we will be ready to merge.

Also, change the name of the PR to **Add Facebook authentication support via `flutter_facebook_auth` dependency** or similar because is what is going to be used by semantic release to describe the change.

Cheers,
Fernando.

2024-02-06 20:16 UTC, ferrarafer commented on pubspec.yaml
> +version: 2.20.0
Revert this change, we are using semantic release which takes care of upgrading the version number.

2024-02-06 20:16 UTC, ferrarafer commented on pubspec.yaml
> +  logger: ^1.1.0
Which is the conflict we have when we upgrade logger package?

2024-02-06 20:16 UTC, ferrarafer commented on CHANGELOG.md
> +
Please, revert this, semantic version takes care of the changelog.

2024-02-06 21:05 UTC, ferrarafer commented on README.md
> +4. Regrenerate your app via the Stacked CLI: `stacked generate`
Typo here, Regrenerate -> Regenerate

2024-02-07 13:17 UTC, n0mad-d3v commented on CHANGELOG.md
> +
Hey @ferrarafer, thanks a lot for the feedback, didn't know!
It's done in the 090d2342d2e5bc91c02cfc1ec6405ed3369af708 ✅

2024-02-07 13:17 UTC, n0mad-d3v commented on README.md
> +4. Regrenerate your app via the Stacked CLI: `stacked generate`
Hey @ferrarafer, indeed!
It's done in the f8aaae611e7c05f98dc8f2ea534f134a35d9dc42 ✅

2024-02-07 13:21 UTC, n0mad-d3v commented on pubspec.yaml
> +  logger: ^1.1.0
Hey @ferrarafer, seems like a mistake indeed. 
I reverted that in the e32f5886f522d91d15cdd379f255f86366446101 ✅

2024-02-07 14:19 UTC, ferrarafer requested changes
Great @n0mad-d3v ! Only two more changes and we are ready.

1. Add `firebase_core` dependency to example project.
2. Execute `dart format --fix --set-exit-if-changed .` on the root of the project to update the format to the conventions.
3. Commit changes

2024-02-07 14:53 UTC, n0mad-d3v commented
Hey @ferrarafer, 
I did the requested changes 😊
1. `firebase_core` dep in e71872217fa1866bd88d8807c446bb72bca7cc29
2. `dart format --fix --set-exit-if-changed .` in 00cadd4e86da0d6757bd5abaab307d19bff81cec (yes sorry, I'm in `-l 150` by default 😅)

Don't hesitate if there is anything else I may do and thanks for the review 🙏

2024-02-07 15:57 UTC, ferrarafer approved these changes

2024-02-07 16:02 UTC, merged

2024-02-07 16:03 UTC, FilledStacks commented
:tada: This PR is included in version 2.20.0 :tada:

The release is available on:
- `v2.20.0`
- [GitHub release](https://github.com/Stacked-Org/firebase_auth/releases/tag/v2.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: