feat: add validateOtpAndLinkPhoneNumber method
Stacked-Org/firebase_auth pull request #26
Opened 2024-10-22 13:10 UTC by ferrarafer

Added `validateOtpAndLinkPhoneNumber` method to allow validation of phone number without implicit sign in of the user. Instead of that, we link the phone number to the existing account.

2024-10-22 13:32 UTC, FilledStacks commented on lib/src/firebase_authentication_service.dart
> +  Future<void> validateOtpAndLinkPhoneNumber(
I don't like that this is void. 

Even if we don't need the result I'd prefer this to be a `FirebaseAuthenticationResult`

2024-10-22 13:33 UTC, FilledStacks commented on lib/src/firebase_authentication_service.dart
> +      throw 'The _mobileVerificationId should not be null here. Verification was probably skipped.';
Instead of throwing here I think we can do 

```dart
return FirebaseAuthenticationResult.error(
        errorMessage: 'Our error message' ,
        exceptionCode: 'custom_code,
      )
```

Add into the comments of the function the code and what it means.

2024-10-22 13:34 UTC, FilledStacks commented on lib/src/firebase_authentication_service.dart
> +      throw FirebaseAuthenticationResult.error(
Lets return here and above instead of throwing. 

I think that's a mistake in the other parts of the code as well.

2024-10-22 13:34 UTC, FilledStacks requested changes
Comments added.

2024-10-22 14:20 UTC, ferrarafer commented on lib/src/firebase_authentication_service.dart
> +  Future<void> validateOtpAndLinkPhoneNumber(
@FilledStacks, where do we get the `FirebaseAuthenticationResult`? We are not logging the user, is already logged. We link the credential with the account if the OTP is valid.

Do you want to return the UserCredential from `linkWithCredential` method?

2024-10-22 14:43 UTC, FilledStacks commented on lib/src/firebase_authentication_service.dart
> +  Future<void> validateOtpAndLinkPhoneNumber(
We can change the type of `void` to `FirebaseAuthenticationResult` and then return the details from linkWithCredential. 

If it doesn't return anything we can use the existing current user to return at that call. 

It's just to keep it consistent with the other functions.

2024-10-24 13:17 UTC, FilledStacks approved these changes, later dismissed
Awesome. 

And thanks for updating those old non typed future functions.

2024-10-24 13:18 UTC, FilledStacks commented
@ferrarafer run dart analyze and fix the errors that are popping up. 

I think it's due to the mocks no being regenerated for the tests

2024-10-24 13:44 UTC, merged

2024-10-24 13:46 UTC, FilledStacks commented
:tada: This PR is included in version 2.21.0 :tada:

The release is available on:
- `v2.21.0`
- [GitHub release](https://github.com/Stacked-Org/firebase_auth/releases/tag/v2.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: